_target_: boltzgen.task.predict.predict.Predict

debug: false

data:
  _target_: boltzgen.task.predict.data_from_generated.FromGeneratedDataModule
  cfg:
    _target_: boltzgen.task.predict.data_from_generated.DataConfig
    tokenizer:
      _target_: boltzgen.data.tokenize.tokenizer.Tokenizer
      atomize_modified_residues: false
    featurizer:
      _target_: boltzgen.data.feature.featurizer.Featurizer

    suffix: .cif
    suffix_metadata: .npz
    suffix_native: _native.cif
    samples_per_target: 1000000000000000
    num_targets: 10000000000000
    moldir: null

    batch_size: 1
    num_workers: 4
    pin_memory: true
  design_dir: null
  return_native: false
  compute_affinity: true
  target_templates: false
  fail_if_no_designs: true
  

keys_dict_out: []

writer:
  _target_: boltzgen.task.predict.writer.AffinityWriter
  design_dir: ${data.design_dir}

trainer:
  accelerator: gpu
  logger: false
  devices: 1
  precision: bf16-mixed

name: affinity_in_eval_affinity
output: null
checkpoint: null
matmul_precision: null
recycling_steps: 3
sampling_steps: 200
diffusion_samples: 5

override:
  validators: null